name: Docs
on: [push, pull_request, workflow_dispatch]
permissions:
    contents: write
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme
          sudo apt install libsuitesparse-dev
          export CPPFLAGS="-I/usr/include/suitesparse"  # <-- NEW STEP
          sudo apt-get install glpk-utils
          pip install -r docs/requirements.txt
      - name: Sphinx build
        run: |
          cd docs
          python3 -m sphinx.cmd.build -M html "source" "_build" 
          cp source/my_theme.css _build/html/_static/css
          cp -r _build/html/ ../public
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true
